[[redirects]]
  from = "https://myinfinitepathways.netlify.app/*"
  to = "https://myinfinitepathways.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://myinfinitepathways.netlify.app"
  to = "https://myinfinitepathways.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200